[pytest]
# Автоматически запускает любые асинхронные тесты (async def) без ручных декораторов
asyncio_mode = auto

# Устанавливает жизненный цикл цикла событий (event loop) на всю сессию тестов.
# Это критически важно для работы нашей фикстуры setup_db с Alembic.
asyncio_default_fixture_loop_scope = session

# Указывает pytest, в какой папке искать файлы с тестами
testpaths = tests

# Флаги запуска: 
# -v (verbose) выводит подробную информацию о каждом тесте
# -s отключает перехват вывода (позволяет видеть ваши print() в консоли при падении тестов)
addopts = -v -s
