"""add_composite_index_to_reviews

Revision ID: 928765e95077
Revises: f6f87b93dc8f
Create Date: 2026-07-01 15:31:26.415070

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "928765e95077"
down_revision: str | Sequence[str] | None = "f6f87b93dc8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_reviews_book_id_created_at", "reviews", ["book_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_reviews_book_id_created_at", table_name="reviews")
    # ### end Alembic commands ###
