"""add_indexes_to_books_and_favorites

Revision ID: 05656389f892
Revises: 928765e95077
Create Date: 2026-07-01 15:42:32.250118

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05656389f892"
down_revision: str | Sequence[str] | None = "928765e95077"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_books_author"), table_name="books")
    op.drop_index(op.f("ix_books_title"), table_name="books")
    op.create_index(
        "idx_books_author_trgm",
        "books",
        ["author"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"author": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_books_title_trgm",
        "books",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_index("idx_books_year_id", "books", ["published_year", "id"], unique=False)
    op.create_index("idx_favorites_user_id_added_at", "favorites", ["user_id", "added_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_favorites_user_id_added_at", table_name="favorites")
    op.drop_index("idx_books_year_id", table_name="books")
    op.drop_index(
        "idx_books_title_trgm", table_name="books", postgresql_using="gin", postgresql_ops={"title": "gin_trgm_ops"}
    )
    op.drop_index(
        "idx_books_author_trgm", table_name="books", postgresql_using="gin", postgresql_ops={"author": "gin_trgm_ops"}
    )
    op.create_index(op.f("ix_books_title"), "books", ["title"], unique=False)
    op.create_index(op.f("ix_books_author"), "books", ["author"], unique=False)
    # ### end Alembic commands ###
